---
title: "Launch Academy FAQ"
type: "challenge"
description: "Render a FAQ accordion using React"
tags: "javascript, react, stateful components"
behaviors:
  - react_on_node
ignore:
- "node_modules/"
- "launch-academy-faq.md"
